sudo: false
script: if [ "$TRAVIS_OS_NAME" = "osx" ]; then make ICEBOX=$HOME/extras/share/icebox simpletest; else make ICEBOX=$HOME/extras/share/icebox test; fi
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gperf
    - libftdi-dev
    - build-essential
    - clang
    - bison
    - flex
    - libreadline-dev
    - gawk
    - tcl-dev
    - libffi-dev
    - git
    - mercurial
    - graphviz
    - xdot
    - pkg-config
    - python
    - python3
    - g++-4.8
    - clang-3.6
before_install:
  - pwd
  - printenv
  - echo HOME=$HOME
  - ls -F $HOME
  - mkdir -p $HOME/extras/bin
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew list; brew install python3 bison gawk gnu-sed libftdi0 libffi graphviz; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi; if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi; fi
  - echo CC=$CC CXX=$CXX
  - git clone git://github.com/steveicarus/iverilog.git
  - (cd iverilog && autoconf && ./configure --prefix=$HOME/extras && make && make install)
  - export PATH=$PATH:$HOME/extras/bin
  - git clone https://github.com/cliffordwolf/icestorm.git
  - (cd icestorm && make && make PREFIX=$HOME/extras install)
  - git clone https://github.com/cliffordwolf/yosys.git
  - (cd yosys && make && make test && make PREFIX=$HOME/extras install)
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
branches:
  except:
    - dummy
